name: publish_release

on:
  #release:
  #  types: [published] # triggers for stable and pre-releases
  push:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  PROJECT_NAMESPACE: 4c-multiphysics

jobs:
  publish_release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Extract version from tag
        run: |
          echo "Github tag name: $TAG"
          VERSION=`echo $TAG | perl -lne 'print "$1" if /^v(\d+\.\d+(?:\.\d+)?(?:-[a-z]+(?:\.\d+)?)?)$/'`
          echo "Extracted version: $VERSION"
          if [[ -z "${VERSION// }" ]]
          then
            echo "Error: Could not extract version from tag name"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        env:
          TAG: 2025.1.1-pre.1 #${{  github.ref_name }}
      - id: compute-dependencies-hash
        uses: ./.github/actions/compute-and-check-dependencies-hash
        with:
          skip-check: 'true'
      # - name: Log in to the Container registry
      #   uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      - name: Add tag to docker image
        uses: ./.github/actions/tag_docker_image
        with:
          image-name: ${{ env.REGISTRY }}/${{ env.PROJECT_NAMESPACE }}/4c-dependencies-ubuntu24.04
          source-tag: ${{ github.ref_name }}
          target-tags: |-
            latest
            ${{ steps.compute-dependencies-hash.outputs.version }}
