name: publish_release

on:
  release:
    types: [published] # triggers for stable and pre-releases

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  PROJECT_NAMESPACE: 4c-multiphysics

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - shell: bash
        name: Echo tags
        run: |
          echo $TAGS
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
    #   - id: compute-dependencies-hash
    #     uses: ./.github/actions/compute-and-check-dependencies-hash
    #     with:
    #       skip-check: 'true'
    #   - name: Log in to the Container registry
    #     uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
    #     with:
    #       registry: ${{ env.REGISTRY }}
    #       username: ${{ github.actor }}
    #       password: ${{ secrets.GITHUB_TOKEN }}
    #   - name: Pull current Ubuntu 24.04 dependencies image and tag it with latest
    #     run: |
    #       IMAGE_NAME="${{ env.REGISTRY }}/${{ env.PROJECT_NAMESPACE }}/4c-dependencies-ubuntu24.04"
    #       docker pull $IMAGE_NAME:${{ steps.compute-dependencies-hash.outputs.computed_dependencies_hash }}
    #       docker image tag $IMAGE_NAME:${{ steps.compute-dependencies-hash.outputs.computed_dependencies_hash }} $IMAGE_NAME:latest
    #       docker push $IMAGE_NAME:latest
